/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LogowanieRouteImport } from './routes/logowanie'
import { Route as AuthenticatedDodajRouteImport } from './routes/_authenticated/dodaj'
import { Route as AuthenticatedSkanujRouteImport } from './routes/_authenticated/skanuj'
import { Route as AuthenticatedZakupyRouteImport } from './routes/_authenticated/zakupy'
import { Route as AuthenticatedZakupIdRouteImport } from './routes/_authenticated/zakup.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LogowanieRoute = LogowanieRouteImport.update({
  id: '/logowanie',
  path: '/logowanie',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDodajRoute = AuthenticatedDodajRouteImport.update({
  id: '/dodaj',
  path: '/dodaj',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkanujRoute = AuthenticatedSkanujRouteImport.update({
  id: '/skanuj',
  path: '/skanuj',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedZakupyRoute = AuthenticatedZakupyRouteImport.update({
  id: '/zakupy',
  path: '/zakupy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedZakupIdRoute = AuthenticatedZakupIdRouteImport.update({
  id: '/zakup/$id',
  path: '/zakup/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logowanie': typeof LogowanieRoute
  '/dodaj': typeof AuthenticatedDodajRoute
  '/skanuj': typeof AuthenticatedSkanujRoute
  '/zakupy': typeof AuthenticatedZakupyRoute
  '/zakup/$id': typeof AuthenticatedZakupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logowanie': typeof LogowanieRoute
  '/dodaj': typeof AuthenticatedDodajRoute
  '/skanuj': typeof AuthenticatedSkanujRoute
  '/zakupy': typeof AuthenticatedZakupyRoute
  '/zakup/$id': typeof AuthenticatedZakupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/logowanie': typeof LogowanieRoute
  '/_authenticated/dodaj': typeof AuthenticatedDodajRoute
  '/_authenticated/skanuj': typeof AuthenticatedSkanujRoute
  '/_authenticated/zakupy': typeof AuthenticatedZakupyRoute
  '/_authenticated/zakup/$id': typeof AuthenticatedZakupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/logowanie' | '/dodaj' | '/skanuj' | '/zakupy' | '/zakup/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/logowanie' | '/dodaj' | '/skanuj' | '/zakupy' | '/zakup/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/logowanie'
    | '/_authenticated/dodaj'
    | '/_authenticated/skanuj'
    | '/_authenticated/zakupy'
    | '/_authenticated/zakup/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LogowanieRoute: typeof LogowanieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logowanie': {
      id: '/logowanie'
      path: '/logowanie'
      fullPath: '/logowanie'
      preLoaderRoute: typeof LogowanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dodaj': {
      id: '/_authenticated/dodaj'
      path: '/dodaj'
      fullPath: '/dodaj'
      preLoaderRoute: typeof AuthenticatedDodajRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skanuj': {
      id: '/_authenticated/skanuj'
      path: '/skanuj'
      fullPath: '/skanuj'
      preLoaderRoute: typeof AuthenticatedSkanujRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zakupy': {
      id: '/_authenticated/zakupy'
      path: '/zakupy'
      fullPath: '/zakupy'
      preLoaderRoute: typeof AuthenticatedZakupyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zakup/$id': {
      id: '/_authenticated/zakup/$id'
      path: '/zakup/$id'
      fullPath: '/zakup/$id'
      preLoaderRoute: typeof AuthenticatedZakupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDodajRoute: typeof AuthenticatedDodajRoute
  AuthenticatedSkanujRoute: typeof AuthenticatedSkanujRoute
  AuthenticatedZakupyRoute: typeof AuthenticatedZakupyRoute
  AuthenticatedZakupIdRoute: typeof AuthenticatedZakupIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDodajRoute: AuthenticatedDodajRoute,
  AuthenticatedSkanujRoute: AuthenticatedSkanujRoute,
  AuthenticatedZakupyRoute: AuthenticatedZakupyRoute,
  AuthenticatedZakupIdRoute: AuthenticatedZakupIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LogowanieRoute: LogowanieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
